name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Godot version to build for e.g. "4.3"'
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag robotnikdev/godot-rust-ci:${{ github.event.inputs.version }}
